# Generated by Django 4.2.7 on 2026-06-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_blob',
            field=models.TextField(blank=True, help_text='Base64 encoded resume file', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
