# Generated by Django 4.2.7 on 2026-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('job_title', models.CharField(max_length=500)),
                ('employer_name', models.CharField(max_length=255)),
                ('employer_logo', models.URLField(blank=True, null=True)),
                ('employer_website', models.URLField(blank=True, null=True)),
                ('job_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('job_employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job_apply_link', models.URLField()),
                ('job_description', models.TextField()),
                ('job_is_remote', models.BooleanField(default=False, null=True)),
                ('job_posted_at_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('job_posted_at_datetime_utc', models.DateTimeField(blank=True, null=True)),
                ('job_location', models.CharField(blank=True, max_length=255, null=True)),
                ('job_city', models.CharField(blank=True, max_length=100, null=True)),
                ('job_state', models.CharField(blank=True, max_length=100, null=True)),
                ('job_country', models.CharField(blank=True, max_length=10, null=True)),
                ('job_benefits', models.JSONField(blank=True, null=True)),
                ('job_salary_string', models.CharField(blank=True, max_length=100, null=True)),
                ('job_min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('job_salary_period', models.CharField(blank=True, max_length=20, null=True)),
                ('job_highlights', models.JSONField(blank=True, null=True)),
                ('required_technologies', models.JSONField(blank=True, null=True)),
                ('employer_reviews', models.JSONField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_jobs',
                'ordering': ['-job_posted_at_datetime_utc', '-fetched_at'],
                'indexes': [models.Index(fields=['job_id'], name='external_jo_job_id_12dadb_idx'), models.Index(fields=['job_posted_at_datetime_utc'], name='external_jo_job_pos_ea6a60_idx'), models.Index(fields=['job_location'], name='external_jo_job_loc_2f29f5_idx'), models.Index(fields=['employer_name'], name='external_jo_employe_f22469_idx')],
            },
        ),
    ]
