# Generated by Django 4.2.7 on 2026-07-12 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company'),
        ('jobs', '0005_companysync_delete_externaljob_job_employer_logo_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_company_8219f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_is_exte_56a758_idx',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_logo',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_reviews',
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer_website',
        ),
        migrations.RemoveField(
            model_name='job',
            name='is_external',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_benefits',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_highlights',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_is_remote',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_publisher',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_range',
        ),
        migrations.AddField(
            model_name='job',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_salary_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='provider',
            field=models.CharField(blank=True, default='PaidAPI', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_job_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='provider_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=20),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company_name'], name='jobs_company_7fe7c5_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['source'], name='jobs_source_a62c67_idx'),
        ),
    ]
